[package]
name = "sisyphus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sailfish = "0.3.3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }